-- ============================================================================
-- OMNICART RELATIONAL DATABASE SCHEMA (MySQL 8.0+)
-- Mapped strictly to the Project ERD & Database Requirements Specification
-- Group Members (Group 21): Kaushal Kishor, Ritik Yadav, Sachin Kumar,
--                           Aditya Kumar, Akash, Mohit Bairwa
-- ============================================================================

CREATE DATABASE IF NOT EXISTS omnicart_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE omnicart_db;

-- ----------------------------------------------------------------------------
-- 1. CUSTOMER ENTITIES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Customer (
    CustomerID VARCHAR(32) NOT NULL,
    FirstName VARCHAR(64) NOT NULL,
    LastName VARCHAR(64) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CustomerID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CustomerPhone (
    CustomerID VARCHAR(32) NOT NULL,
    PhoneNumber VARCHAR(20) NOT NULL,
    PhoneType VARCHAR(32) DEFAULT 'Mobile',
    PRIMARY KEY (CustomerID, PhoneNumber),
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CustomerEmail (
    CustomerID VARCHAR(32) NOT NULL,
    EmailAddress VARCHAR(128) NOT NULL,
    EmailType VARCHAR(32) DEFAULT 'Primary',
    PRIMARY KEY (CustomerID, EmailAddress),
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Address (
    AddressID VARCHAR(32) NOT NULL,
    CustomerID VARCHAR(32) NOT NULL,
    HouseNumber VARCHAR(64),
    Street VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    PINcode VARCHAR(16) NOT NULL,
    IsDefault BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (AddressID),
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS AddressType (
    AddressID VARCHAR(32) NOT NULL,
    CustomerID VARCHAR(32) NOT NULL,
    AddressType VARCHAR(32) NOT NULL DEFAULT 'Home',
    PRIMARY KEY (AddressID, CustomerID),
    FOREIGN KEY (AddressID) REFERENCES Address(AddressID) ON DELETE CASCADE,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ----------------------------------------------------------------------------
-- 2. SELLER ENTITY
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Seller (
    SellerID VARCHAR(32) NOT NULL,
    CompanyName VARCHAR(128) NOT NULL,
    GSTIN VARCHAR(15) NOT NULL,
    ContactEmail VARCHAR(128) NOT NULL,
    ContactPhone VARCHAR(20) NOT NULL,
    City VARCHAR(100) DEFAULT 'India',
    Password VARCHAR(255) NOT NULL DEFAULT 'seller123',
    Rating DECIMAL(3, 2) DEFAULT 4.80,
    PRIMARY KEY (SellerID),
    UNIQUE KEY uq_gstin (GSTIN)
) ENGINE=InnoDB;

-- ----------------------------------------------------------------------------
-- 3. CATEGORY ENTITIES
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Category (
    CategoryID VARCHAR(32) NOT NULL,
    CategoryName VARCHAR(128) NOT NULL,
    Level INT NOT NULL DEFAULT 1,
    PRIMARY KEY (CategoryID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CategoryDesc (
    CategoryID VARCHAR(32) NOT NULL,
    CategoryDescription TEXT NOT NULL,
    PRIMARY KEY (CategoryID),
    FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ----------------------------------------------------------------------------
-- 4. PRODUCT ENTITIES & VISUAL EMBEDDINGS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Product (
    ProductID VARCHAR(32) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    StockQuantity INT NOT NULL DEFAULT 0,
    SellerID VARCHAR(32) NOT NULL,
    CategoryID VARCHAR(32) NOT NULL,
    CurrentPrice DECIMAL(10, 2) NOT NULL,
    OriginalPrice DECIMAL(10, 2) NOT NULL,
    Image VARCHAR(512),
    PRIMARY KEY (ProductID),
    FOREIGN KEY (SellerID) REFERENCES Seller(SellerID) ON DELETE RESTRICT,
    FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ProductImages (
    ImageID INT AUTO_INCREMENT,
    ProductID VARCHAR(32) NOT NULL,
    ProductImages VARCHAR(512) NOT NULL,
    PRIMARY KEY (ImageID),
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Visual Search AI Embeddings Table (As specified in ERD & project requirements)
-- Stores 512-dimensional dense feature vectors generated by OpenAI CLIP / Vision ML model
CREATE TABLE IF NOT EXISTS ProductEmbeddings (
    EmbeddingsID VARCHAR(32) NOT NULL,
    ProductID VARCHAR(32) NOT NULL,
    FeatureVector JSON NOT NULL, -- 512-dimensional L2-normalized float array
    ModelName VARCHAR(64) DEFAULT 'openai/clip-vit-base-patch32',
    Dimensions INT DEFAULT 512,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (EmbeddingsID),
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ----------------------------------------------------------------------------
-- 5. PRICE LEDGER TIME-SERIES (Append-only dynamic price logs)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS PriceLedger (
    LedgerID VARCHAR(32) NOT NULL,
    ProductID VARCHAR(32) NOT NULL,
    Timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PriceFluctuation DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (LedgerID),
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PriceLedgerSource (
    LedgerID VARCHAR(32) NOT NULL,
    ProductID VARCHAR(32) NOT NULL,
    Source VARCHAR(128) NOT NULL,
    PRIMARY KEY (LedgerID, ProductID),
    FOREIGN KEY (LedgerID) REFERENCES PriceLedger(LedgerID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ----------------------------------------------------------------------------
-- 6. ORDER ENTITIES & LINE ITEMS
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `Order` (
    OrderID VARCHAR(32) NOT NULL,
    OrderDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ShippingStatus VARCHAR(32) NOT NULL DEFAULT 'Processing', -- Processing | Shipped | Delivered
    CustomerID VARCHAR(32) NOT NULL,
    ShippingAddressID VARCHAR(32),
    TotalAmount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    DeliveryETA VARCHAR(128),
    PRIMARY KEY (OrderID),
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS OrderPayment (
    OrderID VARCHAR(32) NOT NULL,
    PaymentMethod VARCHAR(128) NOT NULL,
    PaymentStatus VARCHAR(32) NOT NULL DEFAULT 'Completed',
    PRIMARY KEY (OrderID),
    FOREIGN KEY (OrderID) REFERENCES `Order`(OrderID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS OrderDetail (
    DetailID INT AUTO_INCREMENT,
    OrderID VARCHAR(32) NOT NULL,
    ProductID VARCHAR(32) NOT NULL,
    Quantity INT NOT NULL DEFAULT 1,
    ExactLedgerPrice DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (DetailID),
    FOREIGN KEY (OrderID) REFERENCES `Order`(OrderID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- ----------------------------------------------------------------------------
-- 7. SAVED PRODUCTS (Customer Wishlist)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS SavedProduct (
    CustomerID VARCHAR(32) NOT NULL,
    ProductID VARCHAR(32) NOT NULL,
    DateAdded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CustomerID, ProductID),
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Product(ProductID) ON DELETE CASCADE
) ENGINE=InnoDB;
