-- OmniCart ProductEmbeddings Clean Template
-- Product embeddings are dynamically generated by OpenAI CLIP ViT-B/32 model
-- when sellers register new products with image assets.
USE omnicart_db;

-- Ready for custom product embeddings
